### ISSUE TITLE
맥 시동시 자동 실행 

### ISSUE THREAD

**Issue by jacepark12** [moimz/iCoinTicker#1]
현재 잘 쓰고 있고요, 정말 유용한것 같습니다 :)
매번 사이트 들어가는게 귀찮았는데 이제 바로 볼 수 있어서 편리하네요

나중에 맥 재시동시에 자동 실행되면 더 편리할 것 같습니다!

**Comment by arzzcom** [comment]
맥 시작시 자동실행이 swift 로 만드는게 매우매우매우 귀찮더라구요 ㅠ
일단은 추가해볼 생각이지만, 그 전까지는 맥의 설정 > 사용자 및 그룹 > 로그인 항목에서 수동으로 추가하신 후 사용해주세요. ㅠㅠ
<img width="668" alt="2017-06-15 17 55 25" src="https://user-images.githubusercontent.com/4408201/27173498-e11ea9fa-51f3-11e7-9b1c-0c8e3d137f71.png">

**Comment by jacepark12** [comment]
@arzzcom 
네 !!감사합니다 
앞으로도 잘 쓸게요
