### ISSUE TITLE
Can't uncheck 'Hide from the menubar'

### ISSUE THREAD

**Issue by damtsnkff** [moimz/iCoinTicker#12]
Whenever I click on 'Hide from the menubar' to uncheck it, nothing happens and it stays checked.
I tried relaunching the app, didn't work.
<img width="723" alt="screen shot 2017-08-02 at 2 43 04 pm" src="https://user-images.githubusercontent.com/8188697/28874335-b7f06a8c-7791-11e7-87b8-e33eb0674247.png">

**Comment by arzzcom** [comment]
"Hide from menubar" means disappearance all market price on macOS statusbar.
You can check the market you want(Bittrex, in your attached image) and display the market price in status bar.
