### ISSUE TITLE
other currencies?

### ISSUE THREAD

**Issue by peace-white** [moimz/iCoinTicker#15]
Can I see other currencies? Example Waves and OmiseGo :)

**Comment by arzzcom** [comment]
To add a new currency, you need to update the flag image and the coins.plist file.
If you tell me currency you wanted, I will add it.

**Comment by peace-white** [comment]
waves and omise go

**Comment by peace-white** [comment]
geadded?

**Comment by arzzcom** [comment]
Ah? Waves and OmiseGo is coin's name????
Too many coins make me hard.... haha.

**Comment by peace-white** [comment]
hahahah :D https://coinmarketcap.com/assets/omisego/
https://coinmarketcap.com/currencies/waves/

**Comment by peace-white** [comment]
Did you do this? Should I update? :/

**Comment by arzzcom** [comment]
@akbrothers I will update Waves soon.
But Omisego isn't possible yet.
iCoinTicker uses allienworks' coin symbol. (https://github.com/allienworks/cryptocoins)
So, I can't add Omisego until allienworks adds coin symbol.
If allienworks adds coin symbol at next version, I will add Omisego too!

**Comment by arzzcom** [comment]
Waves added!

**Comment by peace-white** [comment]
yes, i see :) thank you....  ( Omise Go please :/ )


@akbrothers I will update Waves soon.But Omisego isn't possible yet.iCoinTicker uses allienworks' coin symbol. (https://github.com/allienworks/cryptocoins)So, I can't add Omisego until allienworks adds coin symbol.If allienworks adds coin symbol at next version, I will add Omisego too!
--
