### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by romanpeters** [moimz/iCoinTicker#3]
You know what would be awesome? 
If you can set a price change notifications for a specified value, integrated with macOS' NC.

I'm already really liking the application, btw :)

**Comment by arzzcom** [comment]
Hi. My English is not good :(
You means support local push? (during app running)
or server push? (notify without app launching like as facebook notification)
Mayby local push can be next version (v3.0.0) :)

And Could you help me for translate to English?
New 3.0.0 version is support language pack like this https://github.com/moimz/iCoinTicker/blob/3.0.0/en.lproj/Localizable.strings

**Comment by romanpeters** [comment]
Local push would probably be good enough. I don't see much benefit in having them while the app is not running.

I've proposed some changes for the language pack #6 .

**Comment by arzzcom** [comment]
Thanks!! 👍 
I try adding local push ASAP.

**Comment by arzzcom** [comment]
![notification](https://user-images.githubusercontent.com/4408201/27819256-5af096f0-60d4-11e7-8fbd-e923ddd7f10c.png)

**Comment by arzzcom** [comment]
<img width="500" alt="2017-07-06 16 04 22" src="https://user-images.githubusercontent.com/4408201/27899631-fc535d1a-6265-11e7-8574-895d7db22dbd.png">

<img width="500" alt="2017-07-06 16 12 21" src="https://user-images.githubusercontent.com/4408201/27899637-004cf9ee-6266-11e7-945d-78742a15291a.png">

**Comment by arzzcom** [comment]
Added notification at v3.0.0
